In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
accident = pd.read_csv('/content/accident[1].csv')

In [3]:
accident.head()

,index,accident_id,ST_CASE,VE_TOTAL,VE_FORMS,PEDS,PERSONS,COUNTY,county_name,CITY,...,A_POLPUR,a_polour_lit,A_POSBAC,a_posbac_lit,A_DIST,a_dist_lit,A_DROWSY,a_drowsy_lit,INDIAN_RES,indian_res_lit
0,0,2012040001,40001,1,1,0,1,19,PIMA,0,...,2,Other Crash,1,Driver With Positive BAC Testing Crash,2,Other Crash,2,Other Crash,0,Not Tribal Lands
1,1,2012040002,40002,1,1,0,2,25,YAVAPAI,90,...,2,Other Crash,1,Driver With Positive BAC Testing Crash,2,Other Crash,2,Other Crash,0,Not Tribal Lands
2,2,2012040003,40003,1,1,1,0,13,MARICOPA,370,...,2,Other Crash,2,All Drivers With ZERO BAC Testing Crash,2,Other Crash,2,Other Crash,0,Not Tribal Lands
3,3,2012040004,40004,2,2,0,2,13,MARICOPA,190,...,2,Other Crash,2,All Drivers With ZERO BAC Testing Crash,2,Other Crash,2,Other Crash,0,Not Tribal Lands
4,4,2012040005,40005,2,2,0,4,19,PIMA,530,...,2,Other Crash,3,Unknown BAC Crash,2,Other Crash,2,Other Crash,0,Not Tribal Lands

In [5]:
accident.shape

(1860, 80)

In [7]:
accident.describe()

,index,accident_id,ST_CASE,VE_TOTAL,VE_FORMS,PEDS,PERSONS,COUNTY,CITY,DAY,...,A_SPCRA,A_PED,A_PED_F,A_PEDAL,A_PEDAL_F,A_POLPUR,A_POSBAC,A_DIST,A_DROWSY,INDIAN_RES
count,1860.000000,1.860000e+03,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,...,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000
mean,929.500000,2.014036e+09,40403.498925,1.384946,1.368817,0.255914,2.231183,17.148925,224.463441,15.247849,...,1.657527,1.811828,1.813441,1.959677,1.959677,1.991398,2.222043,1.912903,1.986559,0.184946
std,537.080069,1.437050e+06,236.785498,0.619904,0.602573,0.486606,1.770081,56.230926,709.181094,8.868981,...,0.474665,0.390955,0.389662,0.196768,0.196768,0.092373,0.820428,0.282053,0.115184,0.388358
min,0.000000,2.012040e+09,40001.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,464.750000,2.013040e+09,40203.000000,1.000000,1.000000,0.000000,1.000000,13.000000,0.000000,8.000000,...,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.750000,2.000000,2.000000,0.000000
50%,929.500000,2.014040e+09,40399.500000,1.000000,1.000000,0.000000,2.000000,13.000000,70.000000,15.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000
75%,1394.250000,2.015041e+09,40601.000000,2.000000,2.000000,0.000000,3.000000,19.000000,370.000000,23.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,0.000000
max,1859.000000,2.016041e+09,40880.000000,6.000000,5.000000,5.000000,19.000000,999.000000,9999.000000,31.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000

In [14]:
accident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1860 entries, 0 to 1859
Data columns (total 80 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           1860 non-null   int64
 1   accident_id     1860 non-null   int64
 2   ST_CASE         1860 non-null   int64
 3   VE_TOTAL        1860 non-null   int64
 4   VE_FORMS        1860 non-null   int64
 5   PEDS            1860 non-null   int64
 6   PERSONS         1860 non-null   int64
 7   COUNTY          1860 non-null   int64
 8   county_name     1860 non-null   object
 9   CITY            1860 non-null   int64
 10  city_name       1860 non-null   object
 11  DAY             1860 non-null   int64
 12  MONTH           1860 non-null   int64
 13  YEAR            1860 non-null   int64
 14  HOUR            1860 non-null   int64
 15  MINUTE          1860 non-null   int64
 16  NHS             1860 non-null   int64
 17  FUNC_SYS        748 non-null    float64
 18  func_sys_lit    1860 non-null   object
 19  ROAD_FNC        1112 non-null   float64
 20  road_fnc_lit    1860 non-null   object
 21  RD_OWNER        748 non-null    float64
 22  rd_owner_lit    1860 non-null   object
 23  TWAY_ID         1860 non-null   object
 24  TWAY_ID2        549 non-null    object
 25  LATITUDE        1860 non-null   float64
 26  LONGITUD        1860 non-null   float64
 27  SP_JUR          1860 non-null   int64
 28  sp_jur_lit      1860 non-null   object
 29  HARM_EV         1860 non-null   int64
 30  harm_ev_lit     1860 non-null   object
 31  MAN_COLL        1860 non-null   int64
 32  man_coll_lit    1860 non-null   object
 33  RELJCT1         1860 non-null   int64
 34  RELJCT2         1860 non-null   int64
 35  TYP_INT         1860 non-null   int64
 36  WRK_ZONE        1860 non-null   int64
 37  REL_ROAD        1860 non-null   int64
 38  LGT_COND        1860 non-null   int64
 39  lgt_cond_lit    1860 non-null   object
 40  WEATHER         1860 non-null   int64
 41  weather_lit     1860 non-null   object
 42  SCH_BUS         1860 non-null   object
 43  CF1             1860 non-null   int64
 44  CF2             1860 non-null   int64
 45  CF3             1860 non-null   int64
 46  cf1_lit         1860 non-null   object
 47  cf2_lit         1860 non-null   object
 48  cf3_lit         1860 non-null   object
 49  FATALS          1860 non-null   int64
 50  A_INTER         1860 non-null   int64
 51  a_inter_lit     1860 non-null   object
 52  A_ROADFC        1860 non-null   int64
 53  a_road_fc_lit   1860 non-null   object
 54  A_TOD           1860 non-null   int64
 55  a_tod_lit       1860 non-null   object
 56  A_DOW           1860 non-null   int64
 57  a_dow_lit       1860 non-null   object
 58  A_LT            1860 non-null   int64
 59  a_lt_lit        1860 non-null   object
 60  A_SPCRA         1860 non-null   int64
 61  a_spcra_lit     1860 non-null   object
 62  A_PED           1860 non-null   int64
 63  a_ped_lit       1860 non-null   object
 64  A_PED_F         1860 non-null   int64
 65  a_ped_f_lit     1860 non-null   object
 66  A_PEDAL         1860 non-null   int64
 67  a_pedal_lit     1860 non-null   object
 68  A_PEDAL_F       1860 non-null   int64
 69  a_pedal_f_lit   1860 non-null   object
 70  A_POLPUR        1860 non-null   int64
 71  a_polour_lit    1860 non-null   object
 72  A_POSBAC        1860 non-null   int64
 73  a_posbac_lit    1860 non-null   object
 74  A_DIST          1860 non-null   int64
 75  a_dist_lit      1860 non-null   object
 76  A_DROWSY        1860 non-null   int64
 77  a_drowsy_lit    1860 non-null   object
 78  INDIAN_RES      1860 non-null   int64
 79  indian_res_lit  1860 non-null   object
dtypes: float64(5), int64(44), object(31)
memory usage: 1.1+ MB

In [15]:
accident.duplicated().sum()

0

In [17]:
accident.isnull().sum()

index             0
accident_id       0
ST_CASE           0
VE_TOTAL          0
VE_FORMS          0
                 ..
a_dist_lit        0
A_DROWSY          0
a_drowsy_lit      0
INDIAN_RES        0
indian_res_lit    0
Length: 80, dtype: int64